name: 'Set Version from Git Tag'
description: 'Updates Cargo.toml version from git tag'
runs:
  using: 'composite'
  steps:
    - name: Set version from git tag
      if: startsWith(github.ref, 'refs/tags/')
      shell: bash
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        VERSION=${VERSION#v}
        echo "Setting version to: $VERSION"
        sed -i.bak "s/^version = \".*\"/version = \"$VERSION\"/" Cargo.toml
        grep "^version" Cargo.toml
