name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          manylinux: auto
          args: --release --out dist --sdist

      - name: Publish
        run: uv publish -t ${{ secrets.PYPI_API_TOKEN }}
